name: WingedWardrobe
options:
  bundleIdPrefix: com.samara
  deploymentTarget:
    iOS: "15.0"
targets:
  WingedWardrobe:
    type: application
    platform: iOS
    sources:
      - WingedWardrobe
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.samara.wingedwardrobe
        INFOPLIST_FILE: WingedWardrobe/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
